name = "bartholomew-template"
spin_version = "1"
version = "0.3.0"
description = "Your new Bartholomew website."
trigger = { type = "http", base = "/" }

[[component]]
id = "bartholomew"
files = [ "content/**/*" , "templates/*", "scripts/*", "config/*", "shortcodes/*"]
[component.source]
url = "https://github.com/fermyon/bartholomew/releases/download/v0.8.0/bartholomew.wasm"
digest = "sha256:ad5ac6215fb67ca122011d2d12840cb69ba80819499641349e92c05ceb65afc1"
[component.trigger]
route = "/..."

[[component]]
id = "fileserver"
files = [ { source = "static/", destination = "/" } ]
[component.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm"
digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375"
[component.trigger]
route = "/static/..."
