name = "bartholomew-template"
spin_version = "1"
version = "0.2.5"
description = "Your new Bartholomew website."
trigger = { type = "http", base = "/" }

[[component]]
source = "modules/bartholomew.wasm"
id = "bartholomew"
files = [ "content/**/*", "templates/*", "scripts/*", "config/*", "shortcodes/*"]
[component.trigger]
route = "/..."

[[component]]
source = "modules/spin_static_fs.wasm"
id = "fileserver"
files = [ { source = "static/", destination = "/" } ]
[component.trigger]
route = "/static/..."
