image:
  registry: ghcr.io
  repository: kingdonb/taking-bartholo
  tag: 0.2.4

ports:
  - name: http
    containerPort: 3000
    protocol: TCP

ingress:
  enabled: true

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1
