image:
  registry: ghcr.io
  repository: kingdonb/taking-bartholo
  tag: main-eb4d2f96-1677468420

ports:
  - name: http
    containerPort: 3000
    protocol: TCP

ingress:
  enabled: true

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true
