name: helm-chart

on:
  push:
    tags:
      - 'chart-*'

jobs:
  helm-push-registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Prepare
        id: prep
        run: |
          BRANCH=${GITHUB_REF##*/}
          TS=$(date +%s)
          REVISION=${GITHUB_SHA::8}
          BUILD_ID="${BRANCH}-${REVISION}-${TS}"
          LATEST_ID=canary
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_ID=${GITHUB_REF/refs\/tags\/chart-/}
            LATEST_ID=latest
          fi
          echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
          echo BUILD_ID=${BUILD_ID} >> $GITHUB_OUTPUT
          echo LATEST_ID=${LATEST_ID} >> $GITHUB_OUTPUT

      - name: Check out code
        id: checkout
        uses: actions/checkout@v3

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: bart
          repository: ${{ github.actor }}/taking-bartholo/helm
          tag: ${{ steps.prep.outputs.BUILD_ID }}
          path: charts/bart
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
