name: spin-publish

on:
  #pull_request:
  push:
    branches:
      - '*'

jobs:
  spin-registry-push:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Spin CLI
        uses: kingdonb/taking-bartholo/action@test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish v1
        id: publish
        run: |
          spin registry push ghcr.io/${{ github.actor }}/taking-bartholo:v1
