name: spin-publish

on:
  #pull_request:
  push:
    branches:
      - main

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Spin CLI
        uses: kingdonb/taking-bartholo/action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish v1
        id: publish
        run: |
          spin registry push ghcr.io/${{ vars.GITHUB_ACTOR }}/taking-bartholo:v1
